import '../state/calculator_controller.dart';
import 'widgets/calculator_key.dart';

const standardCalculatorKeys = [
  '%',
  'CE',
  'C',
  'backspace',
  'reciprocal',
  'square',
  'sqrt',
  '÷',
  '7',
  '8',
  '9',
  '×',
  '4',
  '5',
  '6',
  '−',
  '1',
  '2',
  '3',
  '+',
  'sign',
  '0',
  ',',
  '=',
];

List<String> scientificCalculatorKeys(CalculatorState state) => [
      '2nd',
      'Hyp',
      'angle',
      'C',
      'backspace',
      state.second ? 'cube' : 'square',
      state.second ? 'root' : 'power',
      '10ˣ',
      'eˣ',
      'Mod',
      'reciprocal',
      'abs',
      state.second ? 'cbrt' : 'sqrt',
      'factorial',
      'Exp',
      'sin',
      'cos',
      'tan',
      'pi',
      '÷',
      'ln',
      '7',
      '8',
      '9',
      '×',
      'log',
      '4',
      '5',
      '6',
      '−',
      '(',
      '1',
      '2',
      '3',
      '+',
      ')',
      'sign',
      '0',
      ',',
      '=',
    ];

/// Чем клавиша занята. Знание одно на обе раскладки: столбец действий узнают
/// по знаку, а не по месту в списке.
CalculatorKeyRole calculatorKeyRole(String key) => switch (key) {
      '=' => CalculatorKeyRole.result,
      '÷' || '×' || '−' || '+' => CalculatorKeyRole.operation,
      _ => CalculatorKeyRole.plain,
    };
