import 'holiday_definition.dart';

/// Праздники с постоянной датой. Это данные, а не правила: даты и тексты
/// меняются раз в год и правятся здесь, не задевая расчёта календаря.
const fixedHolidays = <FixedHoliday>[
  FixedHoliday(
      'new_year',
      1,
      1,
      'Новый год',
      'New Year',
      'Первый день нового года.',
      'The first day of the new year.',
      'Государственный праздник и начало новогодних каникул.',
      'A public holiday and the start of the New Year holidays.'),
  FixedHoliday(
      'new_year_holiday_2',
      1,
      2,
      'Новогодние каникулы',
      'New Year holidays',
      'Новогодний праздничный день.',
      'A New Year public holiday.',
      'Официальный день новогодних каникул.',
      'An official day of the New Year holidays.'),
  FixedHoliday(
      'new_year_holiday_3',
      1,
      3,
      'Новогодние каникулы',
      'New Year holidays',
      'Новогодний праздничный день.',
      'A New Year public holiday.',
      'Официальный день новогодних каникул.',
      'An official day of the New Year holidays.'),
  FixedHoliday(
      'new_year_holiday_4',
      1,
      4,
      'Новогодние каникулы',
      'New Year holidays',
      'Новогодний праздничный день.',
      'A New Year public holiday.',
      'Официальный день новогодних каникул.',
      'An official day of the New Year holidays.'),
  FixedHoliday(
      'new_year_holiday_5',
      1,
      5,
      'Новогодние каникулы',
      'New Year holidays',
      'Новогодний праздничный день.',
      'A New Year public holiday.',
      'Официальный день новогодних каникул.',
      'An official day of the New Year holidays.'),
  FixedHoliday(
      'new_year_holiday_6',
      1,
      6,
      'Новогодние каникулы',
      'New Year holidays',
      'Новогодний праздничный день.',
      'A New Year public holiday.',
      'Официальный день новогодних каникул.',
      'An official day of the New Year holidays.'),
  FixedHoliday(
      'orthodox_christmas',
      1,
      7,
      'Рождество Христово',
      'Orthodox Christmas',
      'Православное Рождество.',
      'Orthodox Christmas Day.',
      'Православный праздник Рождества Иисуса Христа.',
      'The Orthodox celebration of the birth of Jesus Christ.'),
  FixedHoliday(
      'new_year_holiday_8',
      1,
      8,
      'Новогодние каникулы',
      'New Year holidays',
      'Новогодний праздничный день.',
      'A New Year public holiday.',
      'Официальный день новогодних каникул.',
      'An official day of the New Year holidays.'),
  FixedHoliday(
      'students_day',
      1,
      25,
      'Татьянин день',
      "Students' Day",
      'День российского студенчества.',
      'Russian Students’ Day.',
      'Праздник российского студенчества и именины Татьян.',
      'A celebration of Russian students and Saint Tatiana.'),
  FixedHoliday(
      'valentines_day',
      2,
      14,
      'День всех влюблённых',
      "Valentine's Day",
      'Популярный праздник влюблённых.',
      'A popular celebration of love.',
      'День, когда близким людям дарят знаки внимания.',
      'A day for sharing affection with loved ones.'),
  FixedHoliday(
      'defender_day',
      2,
      23,
      'День защитника Отечества',
      'Defender of the Fatherland Day',
      'Государственный праздник.',
      'A national public holiday.',
      'Праздник военнослужащих, ветеранов и защитников страны.',
      'A public holiday honoring service members, veterans, and defenders.'),
  FixedHoliday(
      'womens_day',
      3,
      8,
      'Международный женский день',
      "International Women's Day",
      'Государственный праздник.',
      'A national public holiday.',
      'Праздник женщин, весны и уважения.',
      'A celebration of women, spring, and appreciation.'),
  FixedHoliday(
      'april_fools',
      4,
      1,
      'День смеха',
      "April Fools' Day",
      'День добрых шуток.',
      'A day for friendly jokes.',
      'Популярный неофициальный день юмора и добрых розыгрышей.',
      'An informal day of humor and friendly pranks.'),
  FixedHoliday(
      'cosmonautics_day',
      4,
      12,
      'День космонавтики',
      'Cosmonautics Day',
      'Годовщина первого полёта человека в космос.',
      'The anniversary of the first human spaceflight.',
      'Праздник в честь полёта Юрия Гагарина 12 апреля 1961 года.',
      'Celebrates Yuri Gagarin’s first human spaceflight on 12 April 1961.'),
  FixedHoliday(
      'spring_labour_day',
      5,
      1,
      'Праздник Весны и Труда',
      'Spring and Labour Day',
      'Государственный праздник.',
      'A national public holiday.',
      'Праздник весны, мира и труда.',
      'A public celebration of spring, peace, and labour.'),
  FixedHoliday(
      'victory_day',
      5,
      9,
      'День Победы',
      'Victory Day',
      'День Победы в Великой Отечественной войне.',
      'Victory in the Great Patriotic War.',
      'День памяти и празднования Победы 1945 года.',
      'A day of remembrance and celebration of the 1945 Victory.'),
  FixedHoliday(
      'childrens_day',
      6,
      1,
      'День защиты детей',
      "Children's Day",
      'Международный день защиты детей.',
      "International Children's Day.",
      'Праздник, напоминающий о правах и благополучии детей.',
      'A day highlighting children’s rights and well-being.'),
  FixedHoliday(
      'russia_day',
      6,
      12,
      'День России',
      'Russia Day',
      'Государственный праздник.',
      'A national public holiday.',
      'Праздник страны, гражданского мира и единства.',
      'A celebration of the country, civic peace, and unity.'),
  FixedHoliday(
      'family_day',
      7,
      8,
      'День семьи, любви и верности',
      'Day of Family, Love and Fidelity',
      'Российский семейный праздник.',
      'A Russian family celebration.',
      'Праздник семьи, супружеской верности и заботы о близких.',
      'A celebration of family, marital fidelity, and care for loved ones.'),
  FixedHoliday(
      'knowledge_day',
      9,
      1,
      'День знаний',
      'Knowledge Day',
      'Начало учебного года.',
      'The start of the school year.',
      'Традиционный первый день нового учебного года.',
      'The traditional first day of the new school year.'),
  FixedHoliday(
      'teachers_day',
      10,
      5,
      'День учителя',
      "Teachers' Day",
      'Профессиональный праздник учителей.',
      'A professional holiday for teachers.',
      'День благодарности педагогам и наставникам.',
      'A day of appreciation for teachers and mentors.'),
  FixedHoliday(
      'unity_day',
      11,
      4,
      'День народного единства',
      'National Unity Day',
      'Государственный праздник.',
      'A national public holiday.',
      'Праздник гражданской солидарности и единства народа России.',
      'A public holiday celebrating civic solidarity and national unity.'),
  FixedHoliday(
      'new_year_eve',
      12,
      31,
      'Канун Нового года',
      "New Year's Eve",
      'Последний день года.',
      'The final day of the year.',
      'День подготовки к встрече Нового года.',
      'A day for preparing to welcome the new year.'),
  FixedHoliday.folk(
    'old_new_year',
    1,
    14,
    'Старый Новый год',
    'Old New Year',
    'Традиция появилась после перехода России с юлианского на григорианский календарь в 1918 году. Разница между календарями оставила в народной культуре ещё одну новогоднюю ночь — с 13 на 14 января.',
    'The tradition arose after Russia adopted the Gregorian calendar in 1918, leaving a second New Year night on 13–14 January.',
  ),
  FixedHoliday.orthodox(
    'epiphany',
    1,
    19,
    'Крещение Господне',
    'Theophany',
    'Один из двунадесятых праздников посвящён Крещению Иисуса Христа в реке Иордан. В русской традиции с праздником связаны великое освящение воды и крещенские купания.',
    "One of the Twelve Great Feasts commemorates Christ's baptism in the Jordan and is associated with the blessing of water.",
  ),
  FixedHoliday.professional(
    'russian_science_day',
    2,
    8,
    'День российской науки',
    'Russian Science Day',
    'Дата связана с учреждением Петром I Академии наук в 1724 году. Современный праздник установлен в 1999 году к 275-летию Российской академии наук.',
    'The date recalls Peter the Great’s establishment of the Academy of Sciences in 1724; the modern observance was introduced in 1999.',
  ),
  FixedHoliday.professional(
    'diplomats_day',
    2,
    10,
    'День дипломатического работника',
    'Diplomatic Service Day',
    'Праздник установлен в 2002 году. Дата связана с самым ранним упоминанием Посольского приказа в 1549 году — первого постоянного внешнеполитического ведомства Российского государства.',
    'Established in 2002, the date recalls the earliest 1549 reference to the Posolsky Prikaz, Russia’s first permanent foreign-affairs office.',
  ),
  FixedHoliday.orthodox(
    'presentation_of_jesus',
    2,
    15,
    'Сретение Господне',
    'Presentation of Jesus',
    'Двунадесятый праздник вспоминает встречу младенца Иисуса с праведным Симеоном в Иерусалимском храме. Слово «сретение» в церковнославянском языке означает «встреча».',
    'The feast recalls the infant Jesus meeting Simeon in the Temple; the Slavic name literally means “meeting.”',
  ),
  FixedHoliday.military(
    'special_operations_forces_day',
    2,
    27,
    'День Сил специальных операций',
    'Special Operations Forces Day',
    'Памятный день российских Сил специальных операций учреждён указом Президента в 2015 году. Он посвящён военнослужащим подразделений, выполняющих особо сложные задачи.',
    'The Russian military observance was established by presidential decree in 2015 to honor special-operations personnel.',
  ),
  FixedHoliday.professional(
    'world_plumbing_day',
    3,
    11,
    'Всемирный день сантехника',
    'World Plumbing Day',
    'Всемирный совет по сантехнике учредил эту дату в 2010 году. Праздник напоминает о роли сантехников, водоснабжения и канализации в здоровье людей, безопасности городов и сохранении чистой воды.',
    'Created by the World Plumbing Council in 2010, the day highlights plumbing’s role in public health, safe water, and sanitation.',
  ),
  FixedHoliday.military(
    'submariners_day',
    3,
    19,
    'День моряка-подводника',
    'Submariners Day',
    '19 марта 1906 года подводные лодки были выделены в самостоятельный класс кораблей Российского флота. Профессиональный день восстановлен приказом главнокомандующего ВМФ в 1996 году.',
    'On 19 March 1906 submarines became a distinct class of the Russian fleet; the observance was restored in 1996.',
  ),
  FixedHoliday.professional(
    'culture_workers_day',
    3,
    25,
    'День работника культуры',
    'Culture Workers Day',
    'Единый профессиональный день работников музеев, библиотек, театров, домов культуры и других учреждений установлен указом Президента в 2007 году.',
    'The unified professional day for museum, library, theater, and cultural-center workers was established in 2007.',
  ),
  FixedHoliday.military(
    'national_guard_day',
    3,
    27,
    'День войск национальной гвардии',
    'National Guard Troops Day',
    'Дата восходит к созданию в 1811 году внутренней стражи Российской империи. Современное название праздник получил после образования Росгвардии в 2016 году.',
    'The date traces its history to the Imperial Russian Internal Guard created in 1811 and received its current name in 2016.',
  ),
  FixedHoliday.orthodox(
    'annunciation',
    4,
    7,
    'Благовещение Пресвятой Богородицы',
    'Annunciation',
    'Праздник посвящён евангельской вести архангела Гавриила Деве Марии о будущем рождении Иисуса Христа. Он относится к двунадесятым и неизменно отмечается 7 апреля по гражданскому календарю.',
    'The feast commemorates Gabriel’s announcement to Mary that she would give birth to Jesus Christ.',
  ),
  FixedHoliday.professional(
    'fire_service_day',
    4,
    30,
    'День пожарной охраны',
    'Fire Service Day',
    '30 апреля 1649 года царь Алексей Михайлович издал «Наказ о градском благочинии», заложивший основы постоянной противопожарной службы в России. Профессиональный праздник установлен в 1999 году.',
    'The date recalls a 1649 decree by Tsar Alexei Mikhailovich that laid the foundations of Russia’s permanent fire service.',
  ),
  FixedHoliday.professional(
    'radio_day',
    5,
    7,
    'День радио',
    'Radio Day',
    '7 мая 1895 года Александр Попов продемонстрировал в Петербурге прибор для регистрации электромагнитных волн. С 1945 года дата стала праздником работников связи, радио и электронной техники.',
    'The date marks Alexander Popov’s 1895 demonstration of a radio-wave receiver and has honored communications workers since 1945.',
  ),
  FixedHoliday.professional(
    'nurses_day',
    5,
    12,
    'Международный день медицинской сестры',
    'International Nurses Day',
    'Праздник отмечают в день рождения Флоренс Найтингейл, реформатора сестринского дела XIX века. Международный совет медсестёр закрепил современную традицию в 1970-х годах.',
    'Observed on Florence Nightingale’s birthday, the day recognizes the nursing profession and its modern foundations.',
  ),
  FixedHoliday.memorial(
    'slavic_writing_day',
    5,
    24,
    'День славянской письменности и культуры',
    'Day of Slavic Writing and Culture',
    'Дата посвящена равноапостольным Кириллу и Мефодию, создателям славянской письменной традиции IX века. В России государственное празднование было восстановлено в 1991 году.',
    'The date honors Saints Cyril and Methodius, whose ninth-century mission shaped the Slavic written tradition.',
  ),
  FixedHoliday.military(
    'border_guards_day',
    5,
    28,
    'День пограничника',
    'Border Guards Day',
    '28 мая 1918 года была учреждена пограничная охрана РСФСР. Праздник сохраняет память о разных поколениях военнослужащих, охранявших государственную границу.',
    'The date recalls the establishment of the RSFSR border guard on 28 May 1918.',
  ),
  FixedHoliday.memorial(
    'russian_language_day',
    6,
    6,
    'День русского языка',
    'Russian Language Day',
    'Праздник приходится на день рождения Александра Пушкина — 6 июня 1799 года. В России он официально установлен в 2011 году и посвящён русскому языку и литературному наследию.',
    'Observed on Alexander Pushkin’s birthday, the official day was established in 2011 to celebrate the Russian language.',
  ),
  FixedHoliday.professional(
    'social_workers_day',
    6,
    8,
    'День социального работника',
    'Social Workers Day',
    'Дата связана с указом Петра I от 8 июня 1701 года о богадельнях для нуждающихся. Современный профессиональный праздник установлен в 2000 году.',
    'The date recalls Peter the Great’s 1701 decree on care institutions; the modern professional day was established in 2000.',
  ),
  FixedHoliday.memorial(
    'remembrance_and_sorrow_day',
    6,
    22,
    'День памяти и скорби',
    'Day of Remembrance and Sorrow',
    '22 июня 1941 года началась Великая Отечественная война. Памятная дата установлена в 1996 году в честь погибших и всех, кто пережил войну.',
    'The date marks the beginning of the Great Patriotic War on 22 June 1941 and honors its victims and survivors.',
  ),
  FixedHoliday.professional(
    'traffic_police_day',
    7,
    3,
    'День ГАИ',
    'Traffic Police Day',
    '3 июля 1936 года была создана Государственная автомобильная инспекция СССР. Профессиональный день сотрудников дорожной полиции официально закреплён МВД России.',
    'The date marks the creation of the Soviet State Automobile Inspectorate on 3 July 1936.',
  ),
  FixedHoliday.folk(
    'ivan_kupala',
    7,
    7,
    'Иван Купала',
    'Ivan Kupala Day',
    'Народный праздник соединил древние обряды летнего солнцеворота и церковный день Рождества Иоанна Крестителя. С ним связаны костры, вода, травы и легенда о цветке папоротника.',
    'The folk celebration blends midsummer rites with the feast of the Nativity of John the Baptist.',
  ),
  FixedHoliday.memorial(
    'baptism_of_rus',
    7,
    28,
    'День Крещения Руси',
    'Baptism of Rus Day',
    'Памятная дата связана с князем Владимиром и принятием христианства Древней Русью в 988 году. В российский календарь памятных дат она внесена в 2010 году.',
    'The memorial day recalls Prince Vladimir and the Christianization of Kievan Rus in 988.',
  ),
  FixedHoliday.military(
    'airborne_forces_day',
    8,
    2,
    'День ВДВ',
    'Airborne Forces Day',
    '2 августа 1930 года на учениях под Воронежем впервые высадили парашютный десант из двенадцати человек. Этот эпизод принято считать началом отечественных воздушно-десантных войск.',
    'On 2 August 1930 a twelve-man parachute unit landed during exercises near Voronezh, an event regarded as the beginning of Soviet airborne forces.',
  ),
  FixedHoliday.military(
    'air_force_day',
    8,
    12,
    'День Военно-воздушных сил',
    'Air Force Day',
    '12 августа 1912 года был подписан приказ о создании воздухоплавательной части Главного управления Генерального штаба. Эта дата считается отправной точкой российской военной авиации.',
    'The date recalls a 1912 order that created an aeronautical branch of the Russian General Staff.',
  ),
  FixedHoliday.folk(
    'honey_spas',
    8,
    14,
    'Медовый Спас',
    'Honey Spas',
    'Первый из трёх августовских Спасов совпадает с началом Успенского поста. Народная традиция связывает его с окончанием сбора мёда и освящением мёда нового урожая.',
    'The first August “Spas” coincides with the Dormition Fast and is traditionally associated with the new honey harvest.',
  ),
  FixedHoliday.orthodox(
    'transfiguration_apple_spas',
    8,
    19,
    'Преображение Господне · Яблочный Спас',
    'Transfiguration · Apple Spas',
    'Двунадесятый праздник посвящён Преображению Иисуса Христа на горе Фавор. В русской народной традиции к этому дню созревали яблоки нового урожая, которые приносили в храм для освящения.',
    'The Orthodox feast of the Transfiguration became associated in Russian folk tradition with blessing the new apple harvest.',
  ),
  FixedHoliday.memorial(
    'russian_flag_day',
    8,
    22,
    'День Государственного флага России',
    'Russian National Flag Day',
    '22 августа 1991 года российский триколор был восстановлен как национальный флаг. Праздник официально установлен указом Президента в 1994 году.',
    'The date recalls the restoration of the Russian tricolor in 1991; the official observance was established in 1994.',
  ),
  FixedHoliday.orthodox(
    'dormition',
    8,
    28,
    'Успение Пресвятой Богородицы',
    'Dormition of the Mother of God',
    'Двунадесятый праздник завершает двухнедельный Успенский пост и посвящён окончанию земной жизни Богородицы. На Руси этот день издавна был одним из важных рубежей земледельческого года.',
    'The feast concludes the Dormition Fast and commemorates the end of the earthly life of the Mother of God.',
  ),
  FixedHoliday.folk(
    'nut_spas',
    8,
    29,
    'Ореховый Спас',
    'Nut Spas',
    'Третий Спас следует сразу за Успением Богородицы. В народном календаре он совпадал со сбором орехов и завершением жатвы, поэтому его также называли Хлебным Спасом.',
    'The third August “Spas” was associated with gathering nuts and completing the grain harvest.',
  ),
  FixedHoliday.memorial(
    'solidarity_against_terrorism_day',
    9,
    3,
    'День солидарности в борьбе с терроризмом',
    'Day of Solidarity against Terrorism',
    'Памятная дата установлена после трагедии в Беслане 1–3 сентября 2004 года. В этот день вспоминают жертв террористических актов и сотрудников, погибших при спасении людей.',
    'Established after the 2004 Beslan school tragedy, the day remembers victims of terrorism and fallen rescuers.',
  ),
  FixedHoliday.professional(
    'financiers_day',
    9,
    8,
    'День финансиста',
    'Financiers Day',
    '8 сентября 1802 года император Александр I учредил Министерство финансов Российской империи. Современный профессиональный праздник установлен в 2011 году.',
    'The date recalls the establishment of the Russian Empire’s Ministry of Finance in 1802; the modern observance began in 2011.',
  ),
  FixedHoliday.orthodox(
    'nativity_of_theotokos',
    9,
    21,
    'Рождество Пресвятой Богородицы',
    'Nativity of the Mother of God',
    'Первый двунадесятый праздник церковного года посвящён рождению Девы Марии. Он открывает последовательность главных событий православного богослужебного календаря.',
    'The first Great Feast of the liturgical year commemorates the birth of the Virgin Mary.',
  ),
  FixedHoliday.orthodox(
    'exaltation_of_cross',
    9,
    27,
    'Воздвижение Креста Господня',
    'Exaltation of the Holy Cross',
    'Праздник связан с обретением в IV веке Креста, на котором, по церковному преданию, был распят Иисус Христос. В этот день православные соблюдают строгий пост.',
    'The feast recalls the fourth-century finding and exaltation of the Cross of Christ.',
  ),
  FixedHoliday.professional(
    'preschool_workers_day',
    9,
    27,
    'День воспитателя',
    'Preschool Workers Day',
    'Дата выбрана в память об открытии первого детского сада в Санкт-Петербурге в 1863 году. Праздник посвящён воспитателям и всем работникам дошкольного образования.',
    'The date recalls the opening of the first kindergarten in Saint Petersburg in 1863.',
  ),
  FixedHoliday.orthodox(
    'intercession',
    10,
    14,
    'Покров Пресвятой Богородицы',
    'Intercession of the Mother of God',
    'Праздник основан на предании о явлении Богородицы во Влахернском храме Константинополя в X веке. На Руси Покров стал особенно почитаемым и воспринимался как рубеж между осенью и зимой.',
    'The feast recalls a tenth-century apparition in Constantinople and became especially beloved in medieval Rus.',
  ),
  FixedHoliday.professional(
    'police_day',
    11,
    10,
    'День сотрудника органов внутренних дел',
    'Police and Internal Affairs Officers Day',
    'Дата восходит к постановлению о рабочей милиции от 10 ноября 1917 года. После реформы 2011 года привычный День милиции получил современное официальное название.',
    'The date traces back to the establishment of the workers’ militia on 10 November 1917 and received its current name in 2011.',
  ),
  FixedHoliday.professional(
    'accountants_day',
    11,
    21,
    'День бухгалтера',
    'Accountants Day',
    'Неофициальная, но широко распространённая российская дата связана с подписанием 21 ноября 1996 года закона «О бухгалтерском учёте».',
    'The widely observed unofficial Russian date recalls the signing of the 1996 federal accounting law.',
  ),
  FixedHoliday.military(
    'marines_day',
    11,
    27,
    'День морской пехоты',
    'Naval Infantry Day',
    '27 ноября 1705 года Пётр I распорядился сформировать первый в России морской полк. Дата стала профессиональным праздником морских пехотинцев.',
    'The date recalls Peter the Great’s 1705 order to form Russia’s first naval regiment.',
  ),
  FixedHoliday.memorial(
    'unknown_soldier_day',
    12,
    3,
    'День Неизвестного Солдата',
    'Unknown Soldier Day',
    '3 декабря 1966 года прах неизвестного солдата перенесли из братской могилы под Москвой к Кремлёвской стене. Памятная дата учреждена в 2014 году в честь всех безымянных защитников Отечества.',
    'The date recalls the 1966 transfer of an unknown soldier’s remains to the Kremlin Wall and honors all unidentified defenders.',
  ),
  FixedHoliday.professional(
    'lawyers_day',
    12,
    3,
    'День юриста',
    'Lawyers Day',
    'Профессиональный праздник установлен в 2008 году. Дата связана с судебной реформой 1864 года, заложившей основы современного российского судопроизводства и адвокатуры.',
    'Established in 2008, the day is associated with the landmark Russian judicial reform of 1864.',
  ),
  FixedHoliday.orthodox(
    'entry_into_temple',
    12,
    4,
    'Введение во храм Пресвятой Богородицы',
    'Entry of the Mother of God into the Temple',
    'Двунадесятый праздник основан на церковном предании о том, как родители привели трёхлетнюю Марию в Иерусалимский храм и посвятили её Богу.',
    'The feast recalls the tradition of the young Mary being brought to the Temple and dedicated to God.',
  ),
  FixedHoliday.memorial(
    'volunteer_day',
    12,
    5,
    'День добровольца',
    'Volunteer Day',
    'Российский День добровольца учреждён в 2017 году и совпадает с Международным днём добровольцев ООН, который отмечается 5 декабря с 1985 года.',
    'Russia established the observance in 2017 on the same date as the UN International Volunteer Day introduced in 1985.',
  ),
  FixedHoliday.memorial(
    'heroes_of_fatherland_day',
    12,
    9,
    'День Героев Отечества',
    'Heroes of the Fatherland Day',
    'Дата продолжает дореволюционную традицию чествования георгиевских кавалеров 9 декабря. Памятный день восстановлен в 2007 году и посвящён Героям России, СССР и кавалерам высших наград.',
    'Restored in 2007, the day continues the older tradition of honoring recipients of the Order of Saint George.',
  ),
  FixedHoliday.memorial(
    'constitution_day',
    12,
    12,
    'День Конституции России',
    'Russian Constitution Day',
    '12 декабря 1993 года Конституция Российской Федерации была принята всенародным голосованием. Праздник напоминает об основах государственного устройства, правах и свободах граждан.',
    'The Constitution of the Russian Federation was adopted by nationwide vote on 12 December 1993.',
  ),
  FixedHoliday.military(
    'strategic_missile_forces_day',
    12,
    17,
    'День Ракетных войск стратегического назначения',
    'Strategic Missile Forces Day',
    '17 декабря 1959 года в Вооружённых силах СССР был создан новый вид войск — Ракетные войска стратегического назначения. Памятный день посвящён военнослужащим и ветеранам РВСН.',
    'The date recalls the establishment of the Soviet Strategic Missile Forces on 17 December 1959.',
  ),
  FixedHoliday.professional(
    'power_engineers_day',
    12,
    22,
    'День энергетика и электрика',
    'Power Engineers and Electricians Day',
    '22 декабря 1920 года был принят план ГОЭЛРО — первая общегосударственная программа электрификации России. Дата стала профессиональным праздником энергетиков и широко отмечается электриками.',
    'The date marks the adoption of the GOELRO national electrification plan on 22 December 1920 and honors power-industry workers and electricians.',
  ),
  FixedHoliday.professional(
    'rescuers_day',
    12,
    27,
    'День спасателя',
    'Rescuers Day',
    '27 декабря 1990 года был образован Российский корпус спасателей, из которого позднее выросло МЧС России. Профессиональный праздник установлен в 1995 году.',
    'The date marks the creation of the Russian Rescue Corps in 1990, the predecessor of EMERCOM; the observance began in 1995.',
  ),
];
