import 'holiday_definition.dart';

/// Международные и неофициальные дни.
///
/// Отдельный слой: ленты в сетке месяца им не положено — их слишком много, и
/// лента перестала бы что-либо значить. Их место — экран дня, и только когда
/// человек попросил их показывать.
const observanceHolidays = <FixedHoliday>[
  FixedHoliday.observance(
      'obs_braille',
      1,
      4,
      'Всемирный день азбуки Брайля',
      'World Braille Day',
      'Учреждён ООН в память о Луи Брайле и о праве незрячих читать.',
      'A United Nations day honouring Louis Braille and the right of blind people to read.'),
  FixedHoliday.observance(
      'obs_holocaust_remembrance',
      1,
      27,
      'Международный день памяти жертв Холокоста',
      'International Holocaust Remembrance Day',
      'Годовщина освобождения Освенцима, объявленная ООН днём памяти.',
      'The anniversary of the liberation of Auschwitz, declared a day of remembrance by the UN.'),
  FixedHoliday.observance(
      'obs_cancer',
      2,
      4,
      'Всемирный день борьбы против рака',
      'World Cancer Day',
      'День о раннем распознавании болезни и о помощи тем, кто её лечит.',
      'A day about detecting the disease early and supporting those who treat it.'),
  FixedHoliday.observance(
      'obs_women_in_science',
      2,
      11,
      'Международный день женщин и девочек в науке',
      'International Day of Women and Girls in Science',
      'День о равном доступе женщин к научной работе.',
      'A day about equal access for women to work in science.'),
  FixedHoliday.observance(
      'obs_radio',
      2,
      13,
      'Всемирный день радио',
      'World Radio Day',
      'ЮНЕСКО отмечает радио как самое доступное средство связи в мире.',
      'UNESCO marks radio as the most accessible medium in the world.'),
  FixedHoliday.observance(
      'obs_mother_language',
      2,
      21,
      'Международный день родного языка',
      'International Mother Language Day',
      'ЮНЕСКО напоминает о языках, которые исчезают вместе с последними носителями.',
      'UNESCO recalls the languages that vanish along with their last speakers.'),
  FixedHoliday.observance(
      'obs_wildlife',
      3,
      3,
      'Всемирный день дикой природы',
      'World Wildlife Day',
      'День о диких животных и растениях и о торговле, которая им угрожает.',
      'A day about wild animals and plants and the trade that threatens them.'),
  FixedHoliday.observance(
      'obs_consumer_rights',
      3,
      15,
      'Всемирный день защиты прав потребителей',
      'World Consumer Rights Day',
      'День о праве покупателя знать, что он покупает.',
      'A day about the right of a buyer to know what they are buying.'),
  FixedHoliday.observance(
      'obs_happiness',
      3,
      20,
      'Международный день счастья',
      'International Day of Happiness',
      'ООН напоминает, что благополучие людей — цель развития, а не побочный итог.',
      'The UN recalls that human wellbeing is the goal of development, not a by-product.'),
  FixedHoliday.observance(
      'obs_poetry',
      3,
      21,
      'Всемирный день поэзии',
      'World Poetry Day',
      'День, учреждённый ЮНЕСКО в поддержку живого поэтического слова.',
      'A day established by UNESCO in support of living poetry.'),
  FixedHoliday.observance(
      'obs_water',
      3,
      22,
      'Всемирный день водных ресурсов',
      'World Water Day',
      'День о пресной воде и о тех, у кого её нет.',
      'A day about fresh water and about those who have none.'),
  FixedHoliday.observance(
      'obs_theatre',
      3,
      27,
      'Всемирный день театра',
      'World Theatre Day',
      'Праздник сцены, учреждённый Международным институтом театра.',
      'A celebration of the stage, established by the International Theatre Institute.'),
  FixedHoliday.observance(
      'obs_autism',
      4,
      2,
      'Всемирный день распространения информации об аутизме',
      'World Autism Awareness Day',
      'День о принятии людей с аутизмом такими, какие они есть.',
      'A day about accepting autistic people as they are.'),
  FixedHoliday.observance(
      'obs_health',
      4,
      7,
      'Всемирный день здоровья',
      'World Health Day',
      'Годовщина основания Всемирной организации здравоохранения.',
      'The anniversary of the founding of the World Health Organization.'),
  FixedHoliday.observance(
      'obs_monuments',
      4,
      18,
      'Международный день памятников и исторических мест',
      'International Day for Monuments and Sites',
      'День о том, что наследие нужно не только беречь, но и показывать.',
      'A day about heritage that must be shown as well as guarded.'),
  FixedHoliday.observance(
      'obs_earth',
      4,
      22,
      'Международный день Матери-Земли',
      'International Mother Earth Day',
      'День о том, что планета у людей и у всего живого одна на всех.',
      'A day about a planet shared by people and every living thing.'),
  FixedHoliday.observance(
      'obs_book',
      4,
      23,
      'Всемирный день книги и авторского права',
      'World Book and Copyright Day',
      'ЮНЕСКО отмечает чтение и труд тех, кто пишет и издаёт.',
      'UNESCO marks reading and the work of those who write and publish.'),
  FixedHoliday.observance(
      'obs_press_freedom',
      5,
      3,
      'Всемирный день свободы печати',
      'World Press Freedom Day',
      'День о праве говорить и о цене, которую за это платят журналисты.',
      'A day about the right to speak and the price journalists pay for it.'),
  FixedHoliday.observance(
      'obs_red_cross',
      5,
      8,
      'Всемирный день Красного Креста и Красного Полумесяца',
      'World Red Cross and Red Crescent Day',
      'День рождения Анри Дюнана, основателя движения.',
      'The birthday of Henry Dunant, who founded the movement.'),
  FixedHoliday.observance(
      'obs_families',
      5,
      15,
      'Международный день семей',
      'International Day of Families',
      'День о семье как о самой обыкновенной и самой прочной опоре человека.',
      'A day about the family as the plainest and firmest support a person has.'),
  FixedHoliday.observance(
      'obs_museums',
      5,
      18,
      'Международный день музеев',
      'International Museum Day',
      'День, когда музеи открывают двери и напоминают, зачем они есть.',
      'The day museums open their doors and recall why they exist.'),
  FixedHoliday.observance(
      'obs_no_tobacco',
      5,
      31,
      'Всемирный день без табака',
      'World No Tobacco Day',
      'День, предложенный ВОЗ как повод не закурить.',
      'A day proposed by the WHO as a reason not to light up.'),
  FixedHoliday.observance(
      'obs_environment',
      6,
      5,
      'Всемирный день окружающей среды',
      'World Environment Day',
      'Главный экологический день Организации Объединённых Наций.',
      'The principal environmental day of the United Nations.'),
  FixedHoliday.observance(
      'obs_oceans',
      6,
      8,
      'Всемирный день океанов',
      'World Oceans Day',
      'День о море, которое кормит и дышит за всю планету.',
      'A day about the sea that feeds and breathes for the whole planet.'),
  FixedHoliday.observance(
      'obs_elder_abuse',
      6,
      15,
      'Всемирный день борьбы с жестоким обращением с пожилыми',
      'World Elder Abuse Awareness Day',
      'День о том, что старость не отменяет права на защиту.',
      'A day about old age never cancelling the right to protection.'),
  FixedHoliday.observance(
      'obs_refugees',
      6,
      20,
      'Всемирный день беженцев',
      'World Refugee Day',
      'День о тех, кто ушёл из дома не по своей воле.',
      'A day about those who left home against their will.'),
  FixedHoliday.observance(
      'obs_yoga',
      6,
      21,
      'Международный день йоги',
      'International Day of Yoga',
      'День, учреждённый ООН по предложению Индии.',
      'A day established by the UN at the proposal of India.'),
  FixedHoliday.observance(
      'obs_drug_abuse',
      6,
      26,
      'Международный день борьбы с наркоманией',
      'International Day against Drug Abuse',
      'День ООН против злоупотребления наркотиками и их незаконного оборота.',
      'A UN day against drug abuse and illicit trafficking.'),
  FixedHoliday.observance(
      'obs_kiss',
      7,
      6,
      'Всемирный день поцелуя',
      'World Kiss Day',
      'Неофициальный праздник, пришедший из Великобритании и разошедшийся по миру.',
      'An unofficial celebration that started in Britain and spread around the world.'),
  FixedHoliday.observance(
      'obs_population',
      7,
      11,
      'Всемирный день народонаселения',
      'World Population Day',
      'День ООН, отмеченный, когда население Земли перешагнуло пять миллиардов.',
      'A UN day marking the moment the population of the Earth passed five billion.'),
  FixedHoliday.observance(
      'obs_chess',
      7,
      20,
      'Международный день шахмат',
      'International Chess Day',
      'Годовщина основания Международной шахматной федерации.',
      'The anniversary of the founding of the International Chess Federation.'),
  FixedHoliday.observance(
      'obs_friendship',
      7,
      30,
      'Международный день дружбы',
      'International Day of Friendship',
      'День ООН о дружбе между людьми, странами и культурами.',
      'A UN day about friendship between people, countries and cultures.'),
  FixedHoliday.observance(
      'obs_cats',
      8,
      8,
      'Всемирный день кошек',
      'World Cat Day',
      'Неофициальный, но повсеместно отмечаемый кошачий праздник.',
      'An unofficial but widely kept celebration of cats.'),
  FixedHoliday.observance(
      'obs_kiss_and_make_up',
      8,
      25,
      'День «Поцелуемся и помиримся»',
      'Kiss and Make Up Day',
      'Неофициальный день, придуманный как повод помириться с теми, с кем в ссоре.',
      'An unofficial day meant as a reason to make peace with those you have fallen out with.'),
  FixedHoliday.observance(
      'obs_youth',
      8,
      12,
      'Международный день молодёжи',
      'International Youth Day',
      'День ООН о молодых людях и их месте в общем деле.',
      'A UN day about young people and their place in common affairs.'),
  FixedHoliday.observance(
      'obs_humanitarian',
      8,
      19,
      'Всемирный день гуманитарной помощи',
      'World Humanitarian Day',
      'День памяти о тех, кто помогает в местах бедствий и войн.',
      'A day of remembrance for those who help in disaster and war.'),
  FixedHoliday.observance(
      'obs_nuclear_tests',
      8,
      29,
      'Международный день действий против ядерных испытаний',
      'International Day against Nuclear Tests',
      'Годовщина закрытия Семипалатинского полигона.',
      'The anniversary of the closure of the Semipalatinsk test site.'),
  FixedHoliday.observance(
      'obs_charity',
      9,
      5,
      'Международный день благотворительности',
      'International Day of Charity',
      'День памяти матери Терезы, выбранный ООН для этой даты.',
      'A day in memory of Mother Teresa, chosen by the UN for this date.'),
  FixedHoliday.observance(
      'obs_literacy',
      9,
      8,
      'Международный день распространения грамотности',
      'International Literacy Day',
      'День ЮНЕСКО о праве каждого уметь читать и писать.',
      'A UNESCO day about the right of everyone to read and write.'),
  FixedHoliday.observance(
      'obs_peace',
      9,
      21,
      'Международный день мира',
      'International Day of Peace',
      'День прекращения огня и ненасилия, объявленный ООН.',
      'A day of ceasefire and non-violence declared by the UN.'),
  FixedHoliday.observance(
      'obs_tourism',
      9,
      27,
      'Всемирный день туризма',
      'World Tourism Day',
      'День, учреждённый Всемирной туристской организацией.',
      'A day established by the World Tourism Organization.'),
  FixedHoliday.observance(
      'obs_translation',
      9,
      30,
      'Международный день переводчика',
      'International Translation Day',
      'День памяти Иеронима Стридонского, переводчика Библии.',
      'A day in memory of Jerome of Stridon, who translated the Bible.'),
  FixedHoliday.observance(
      'obs_older_persons',
      10,
      1,
      'Международный день пожилых людей',
      'International Day of Older Persons',
      'День ООН о достоинстве и участии старших.',
      'A UN day about the dignity and participation of older people.'),
  FixedHoliday.observance(
      'obs_animals',
      10,
      4,
      'Всемирный день защиты животных',
      'World Animal Day',
      'День святого Франциска Ассизского, покровителя животных.',
      'The feast of Francis of Assisi, patron of animals.'),
  FixedHoliday.observance(
      'obs_teachers_world',
      10,
      5,
      'Всемирный день учителя',
      'World Teachers Day',
      'День ЮНЕСКО о положении учителей во всём мире.',
      'A UNESCO day about the standing of teachers worldwide.'),
  FixedHoliday.observance(
      'obs_mental_health',
      10,
      10,
      'Всемирный день психического здоровья',
      'World Mental Health Day',
      'День о том, что душевное здоровье лечится, а не скрывается.',
      'A day about mental health being treated rather than hidden.'),
  FixedHoliday.observance(
      'obs_food',
      10,
      16,
      'Всемирный день продовольствия',
      'World Food Day',
      'Годовщина основания Продовольственной и сельскохозяйственной организации ООН.',
      'The anniversary of the founding of the UN Food and Agriculture Organization.'),
  FixedHoliday.observance(
      'obs_cities',
      10,
      31,
      'Всемирный день городов',
      'World Cities Day',
      'День ООН о том, как живут и растут города.',
      'A UN day about how cities live and grow.'),
  FixedHoliday.observance(
      'obs_kindness',
      11,
      13,
      'Всемирный день доброты',
      'World Kindness Day',
      'День о простых поступках, которые ничего не стоят и многое меняют.',
      'A day about small acts that cost nothing and change much.'),
  FixedHoliday.observance(
      'obs_tolerance',
      11,
      16,
      'Международный день терпимости',
      'International Day for Tolerance',
      'День ЮНЕСКО о праве быть непохожим.',
      'A UNESCO day about the right to be unlike others.'),
  FixedHoliday.observance(
      'obs_children',
      11,
      20,
      'Всемирный день ребёнка',
      'World Children Day',
      'Годовщина принятия Конвенции о правах ребёнка.',
      'The anniversary of the Convention on the Rights of the Child.'),
  FixedHoliday.observance(
      'obs_television',
      11,
      21,
      'Всемирный день телевидения',
      'World Television Day',
      'День ООН о телевидении как о зеркале и как о силе.',
      'A UN day about television as both a mirror and a force.'),
  FixedHoliday.observance(
      'obs_aids',
      12,
      1,
      'Всемирный день борьбы со СПИДом',
      'World AIDS Day',
      'День о болезни, о лечении и о людях, которых нельзя отталкивать.',
      'A day about the illness, its treatment and people who must not be pushed away.'),
  FixedHoliday.observance(
      'obs_disabilities',
      12,
      3,
      'Международный день инвалидов',
      'International Day of Persons with Disabilities',
      'День ООН о среде, приспособленной для всех.',
      'A UN day about an environment fit for everyone.'),
  FixedHoliday.observance(
      'obs_human_rights',
      12,
      10,
      'День прав человека',
      'Human Rights Day',
      'Годовщина Всеобщей декларации прав человека.',
      'The anniversary of the Universal Declaration of Human Rights.'),
  FixedHoliday.observance(
      'obs_migrants',
      12,
      18,
      'Международный день мигранта',
      'International Migrants Day',
      'День ООН о людях, которые живут не там, где родились.',
      'A UN day about people who live where they were not born.'),
];
